version: "3.8"

x-redash-service: &redash-service-template
    image: redash/redash:latest
    depends_on:
        - redash-postgres-service
        - redash-redis-service
    env_file: ./variables.env
    networks:
        - data-diff-system
    deploy:
        resources:
            limits:
                cpus: '0.25'
                memory: 1024M
            reservations:
                cpus: '0.15'
                memory: 512M
    # restart: always

services:

    redash-server-service:
        <<: *redash-service-template
        command: server 
        ports:
            - "5000:5000"
        environment:
            REDASH_WEB_WORKERS: 1

    redash-temporary-createdb:
        <<: *redash-service-template
        command: create_db 
            
    redash-scheduler-service:
        <<: *redash-service-template
        command: scheduler
        environment:
            QUEUES: "celery"
            WORKERS_COUNT: 1

    redash-scheduled_worker-service:
        <<: *redash-service-template
        command: worker
        environment:
            QUEUES: "scheduled_queries,schemas"
            WORKERS_COUNT: 1

    redash-adhoc_worker-service:
        <<: *redash-service-template
        command: worker
        environment:
            QUEUES: "queries"
            WORKERS_COUNT: 1

    redash-redis-service:
        image: redis:5.0-alpine
        networks:
            - data-diff-system
    
    redash-postgres-service:
        image: postgres:9.6-alpine
        env_file: ./variables.env
        volumes:
            - postgres-redash-data:/var/lib/postgresql/data
        networks:
            - data-diff-system


    postgres-service:
        container_name: postgres-container
        image: postgres
        hostname: postgres-server
        # work_mem: less tmp files
        # maintenance_work_mem: improve table-level op perf
        # max_wal_size: allow more time before merging to heap
        command: >
            -c work_mem=1GB -c maintenance_work_mem=1GB -c max_wal_size=8GB
        restart: always
        volumes:
            - postgresql-data:/var/lib/postgresql/data:delegated
        ports:
            - '5432:5432'
        expose:
            - '5432'
        env_file:
            - ./variables.env
        tty: true
        networks:
            - data-diff-system

    clickhouse-service:
        container_name: clickhouse-container
        image: clickhouse/clickhouse-server
        hostname: clickhouse-server
        restart: always
        volumes:
            - clickhouse-data:/var/lib/clickhouse:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 262144
                hard: 262144
        ports:
            - '8123:8123'
            - '9000:9000'
        expose:
            - '8123'
            - '9000'
        env_file:
            - ./variables.env
        tty: true
        networks:
            - data-diff-system

    presto-service:
        container_name: presto-container
        hostname: presto-server
        build:
            context: .
            dockerfile: ./Dockerfile.presto.0.284
        volumes:
            - ./volumes/configs/presto:/opt/presto/etc:ro
        ports:
            - '8080:8080'
        tty: true
        networks:
            - data-diff-system

    trino-service:
        container_name: trino-container
        image: trinodb/trino
        hostname: trino-server
        ports:
            - '8081:8081'
            - '8082:8080'
        volumes:
            - ./volumes/configs/trino/etc:/etc/trino:ro
        networks:
            - data-diff-system

    vertica-service:
        container_name: vertica-container
        image: vertica/vertica-ce
        hostname: vertica-server
        restart: always
        volumes:
            - vertica-data:/data:delegated
        ports:
            - '5433:5433'
            - '5444:5444'
        expose:
            - '5433'
            - '5444'
        env_file:
            - ./variables.env
        tty: true
        networks:
            - data-diff-system

volumes:
    postgres-redash-data:
    postgresql-data:
    clickhouse-data:
    vertica-data:
networks:
    data-diff-system:
        driver: bridge